"""Asset registry: cataloging, deduplication, and embedding lookup."""

from content_lab_assets.planner import (
    AssetPackPlan,
    AssetPackPlanInput,
    AssetPackPlannedSpec,
    generate_asset_pack_plan,
    validate_requested_asset_mix,
)
from content_lab_assets.registry import (
    AlphaMode,
    AssetKind,
    AssetRecord,
    AssetRegistry,
    AssetSource,
    AssetTransparencyMetadata,
    AssetVisualMetadata,
    GenerateDecision,
    MediaType,
    Phase1AssetRegistryStore,
    ReuseExactDecision,
    aspect_ratio_from_dimensions,
    build_generation_idempotency_key,
    detect_png_transparency,
    detect_png_visual_metadata,
    infer_media_type_for_asset_kind,
    is_ready_asset_status,
    resolve_phase1_asset,
    validate_asset_kind_media_type,
)
from content_lab_assets.store import RunwayAssetStore, SQLRunwayAssetStore, StoredRunwayGeneration

__all__ = [
    "AlphaMode",
    "AssetKind",
    "AssetPackPlan",
    "AssetPackPlanInput",
    "AssetPackPlannedSpec",
    "AssetRecord",
    "AssetRegistry",
    "AssetSource",
    "AssetTransparencyMetadata",
    "AssetVisualMetadata",
    "GenerateDecision",
    "MediaType",
    "Phase1AssetRegistryStore",
    "RunwayAssetStore",
    "ReuseExactDecision",
    "SQLRunwayAssetStore",
    "StoredRunwayGeneration",
    "aspect_ratio_from_dimensions",
    "build_generation_idempotency_key",
    "detect_png_transparency",
    "detect_png_visual_metadata",
    "generate_asset_pack_plan",
    "infer_media_type_for_asset_kind",
    "is_ready_asset_status",
    "resolve_phase1_asset",
    "validate_requested_asset_mix",
    "validate_asset_kind_media_type",
]
